### ISSUE TITLE
README.md not rendered properly on github page

### ISSUE THREAD

**Issue by myood** [j1and1/GodotGooglePlayGamesServices#1]
Hey,

I was about to try your plugin, but the instruction does not print itself properly on the github page.

This part:

  ```
<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="<YOUR_APPLICATION_ID_GOES_HERE>" />
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
    ```

is empty on the main page

**Comment by j1and1** [comment]
Hey! Thank you for letting me know and fixing my stupid compilation errors :+1: , I should've checked before commiting
